# Generated by Django 4.2 on 2024-01-12 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_personas_municipio_residencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='fecha_creacion',
            field=models.DateTimeField(verbose_name='default= timezome.now()-timedelta(hours=5'),
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('especie', models.CharField(choices=[('P', 'perro'), ('G', 'gato'), ('C', 'conejo'), ('I', 'iguana')], max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('propietario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mascotas', to='personas.personas')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animales',
                'db_table': 'animal',
                'managed': True,
            },
        ),
    ]
